# Generated by Django 4.2.8 on 2023-12-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_applicant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.CharField(default='lagos', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='state',
            field=models.CharField(default='lagos', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='zip_code',
            field=models.CharField(default='89076', max_length=10),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Id_document',
            field=models.CharField(choices=[("Driver's License", "Driver's License"), ('Passport', 'Passport'), ('State ID', 'State ID')], max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Job_aspired',
            field=models.CharField(choices=[('Personal Assistant', 'Personal assistant'), ('Data Entry', 'Data Entry'), ('Mystery Shopper', 'Mystery Shopper'), ('Virtual Assistant', 'Virtual Assistant')], max_length=100),
        ),
    ]
