# Generated by Django 4.2.8 on 2023-12-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_applicant_city_alter_applicant_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='upload',
            field=models.FileField(default='hmll', upload_to='resume'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Id_image',
            field=models.ImageField(upload_to='Documents'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
