# Generated by Django 4.2.8 on 2023-12-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_applicant_upload_alter_applicant_id_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='upload',
            field=models.FileField(upload_to='resume'),
        ),
    ]
